apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: my-task-1
spec:
  inputs:
    resources:
      - name: workspace
        type: git
        targetPath: repo
    params:
      - name: param1
        type: string
        description: Some parameter
        default: undefinedInTask
      - name: param2
        type: string
        description: Some parameter
        default: undefinedInTask
  steps:
    - name: step-one
      image: opensuse/leap:15.1
      command:
        - echo
      args:
        - "hello from task with params $(inputs.params.param1) and $(inputs.params.param2)"
    - name: step-two
      image: opensuse/leap:15.1
      script: |
        #!/bin/bash
        set -x
        ls -la /
        ls -la /workspace
        cat /workspace/repo/sample-1/message.txt
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  resources:
    - name: source-repo
      type: git
  params:
    - name: param1
      type: string
      description: Some parameter
      default: undefinedInPipeline
    - name: param2
      type: string
      description: Some parameter
      default: undefinedInPipeline
  tasks:
    - name: task-one
      taskRef:
        name: my-task-1
      resources:
        inputs:
          - name: workspace
            resource: source-repo
      params:
        - name: param1
          value: "$(params.param1)"
        - name: param2
          value: "$(params.param2)"