apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: my-trigger-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: myParam
      value: $(body.my-param)
    - name: myHeader
      value: $(header.X-My-Header)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository URL
    - name: myParam
      description: A sample parameter from the JSON payload
      default: undefinedInTrigger
    - name: myHeader
      description: A sample parameter from the HTTP headers
      default: undefinedInTrigger
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: my-triggered-run
      spec:
        pipelineRef:
          name: my-pipeline
        serviceAccountName: 'default'
        resources:
          - name: source-repo
            #resourceRef:
            #  name: my-git
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitrevision)
                - name: url
                  value: $(params.gitrepositoryurl)
        params:
          - name: param1
            value: $(params.myParam)
          - name: param2
            value: $(params.myHeader)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: my-listener
spec:
  serviceAccountName: my-account
  triggers:
    - name: trigger-one
      binding:
        name: my-trigger-binding
      template:
        name: my-trigger-template
